name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --trace

      - name: Link check (soft)
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: false
          args: >-
            --user-agent 'curl/7.54'
            --exclude 'https://scholar.google.com'
            --exclude 'https://www.researchgate.net'
            --exclude 'https://doi.org'
            --exclude-mail
            --retry-count 2
            --max-concurrency 6
            --verbose --no-progress '_site/**/*.html'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
